# certificate-api.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-admin-gateway-cert  # Уникальное имя для ресурса Certificate
  namespace: nifi                # Важно! Секрет создастся в namespace nifi
spec:
  secretName: nifi-admin-gateway-tls-secret  # Имя создаваемого TLS-секрета (должно совпадать с secretName в Ingress!)
  commonName: API.DOMEN.RU
  dnsNames:
    - API.DOMEN.RU
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod       # Тот же Issuer, который уже работает
  usages:
    - server auth
    - client auth                # Оставляем, если вдруг понадобится mTLS на уровне Ingress
    