# keycloak-tls-secret.yaml

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-secret
  namespace: keycloak
spec:
  secretName: keycloak-tls-secret
  commonName: KEYCLOAK.DOMEN.RU
  dnsNames:
    - KEYCLOAK.DOMEN.RU
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
    - server auth
    - client auth