apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-tls-secret
  namespace: nifi
spec:
  secretName: nifi-tls-secret
  commonName: NIFI.DOMEN.RU
  dnsNames:
    - NIFI.DOMEN.RU
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  usages:
    - server auth
    - client auth
