package resources_gen

import (
	"context"
	"strings"

	"terraform-provider-nubes/internal/core"
	"terraform-provider-nubes/internal/resources_core"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Code generated by tools/gen. DO NOT EDIT.
// Service: mariadb
// Service ID: 115

var _ resource.Resource = &MariadbResource{}
var _ resource.ResourceWithModifyPlan = &MariadbResource{}

type MariadbResource struct {
	client *core.UniversalClient
}

type MariadbModel struct {
	ID                        types.String `tfsdk:"id"`
	ResourceName              types.String `tfsdk:"resource_name"`
	ResourceRealm             types.String `tfsdk:"resource_realm"`
	ResourceCPU               types.Int64  `tfsdk:"resource_c_p_u"`
	ResourceMemory            types.Int64  `tfsdk:"resource_memory"`
	ResourceDisk              types.Int64  `tfsdk:"resource_disk"`
	ResourceInstances         types.Int64  `tfsdk:"resource_instances"`
	NeedExternalAddressMaster types.Bool   `tfsdk:"need_external_address_master"`
	IpSpaceNameMaster         types.String `tfsdk:"ip_space_name_master"`
	ExtBACKUPSCHEDULE         types.String `tfsdk:"ext__b_a_c_k_u_p__s_c_h_e_d_u_l_e"`
	AppVersion                types.String `tfsdk:"app_version"`
	AutoScale                 types.Bool   `tfsdk:"auto_scale"`
	AutoScalePercentage       types.Int64  `tfsdk:"auto_scale_percentage"`
	AutoScaleTechWindow       types.Int64  `tfsdk:"auto_scale_tech_window"`
	AutoScaleQuotaGb          types.Int64  `tfsdk:"auto_scale_quota_gb"`
	S3Uid                     types.String `tfsdk:"s3_uid"`
	DeleteMode                types.String `tfsdk:"delete_mode"`
	ResumeIfExists            types.Bool   `tfsdk:"resume_if_exists"`
}

func NewMariadbResource() resource.Resource {
	return &MariadbResource{}
}

func (r *MariadbResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mariadb"
}

func (r *MariadbResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id":            schema.StringAttribute{Computed: true},
		"resource_name": schema.StringAttribute{Required: true},
		"resource_realm": schema.StringAttribute{
			Required: true,
		},
		"resource_c_p_u": schema.Int64Attribute{
			Required: true,
		},
		"resource_memory": schema.Int64Attribute{
			Required: true,
		},
		"resource_disk": schema.Int64Attribute{
			Required: true,
		},
		"resource_instances": schema.Int64Attribute{
			Required: true,
		},
		"need_external_address_master": schema.BoolAttribute{
			Required: true,
		},
		"ip_space_name_master": schema.StringAttribute{
			Optional: true,
		},
		"ext__b_a_c_k_u_p__s_c_h_e_d_u_l_e": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("0 * * * *"),
		},
		"app_version": schema.StringAttribute{
			Required: true,
		},
		"auto_scale": schema.BoolAttribute{
			Required: true,
		},
		"auto_scale_percentage": schema.Int64Attribute{
			Optional: true,
			Computed: true,
			Default:  int64default.StaticInt64(10),
		},
		"auto_scale_tech_window": schema.Int64Attribute{
			Optional: true,
			Computed: true,
			Default:  int64default.StaticInt64(0),
		},
		"auto_scale_quota_gb": schema.Int64Attribute{
			Optional: true,
			Computed: true,
			Default:  int64default.StaticInt64(1),
		},
		"s3_uid": schema.StringAttribute{
			Required: true,
		},
		"delete_mode": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("state_only"),
		},
		"resume_if_exists": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(true),
		},
	}

	resp.Schema = schema.Schema{Attributes: attrs}
}

func (r *MariadbResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if r.client == nil {
		return
	}

	var config *MariadbModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if config == nil {
		return
	}

	var state *MariadbModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state != nil && !state.ID.IsNull() && !state.ID.IsUnknown() {
		return
	}

	if config.ResourceName.IsNull() || config.ResourceName.IsUnknown() {
		return
	}
	resumeIfExists := true
	if !config.ResumeIfExists.IsNull() && !config.ResumeIfExists.IsUnknown() {
		resumeIfExists = config.ResumeIfExists.ValueBool()
	}

	existing, err := r.client.FindInstanceByDisplayName(ctx, 115, config.ResourceName.ValueString())
	if err != nil || existing == nil {
		return
	}

	if !resumeIfExists {
		resp.Diagnostics.AddError(
			"RESOURCE WITH SAME NAME EXISTS",
			"A resource with the same resource_name already exists. Set resume_if_exists=true to adopt or choose a different name.",
		)
		return
	}

	status := strings.ToLower(existing.ExplainedStatus)
	if strings.Contains(status, "suspend") {
		resp.Diagnostics.AddWarning(
			"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
			"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
		)
		return
	}

	resp.Diagnostics.AddWarning(
		"RESOURCE WITH SAME NAME EXISTS",
		"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
	)
}

func (r *MariadbResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data MariadbModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resourceName := data.ResourceName.ValueString()
	if r.client != nil && !data.ResumeIfExists.IsNull() && !data.ResumeIfExists.IsUnknown() && data.ResumeIfExists.ValueBool() {
		existing, err := r.client.FindInstanceByDisplayName(ctx, 115, resourceName)
		if err == nil && existing != nil {
			status := strings.ToLower(existing.ExplainedStatus)
			if strings.Contains(status, "suspend") {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
					"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			} else {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS",
					"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			}
		}
	}

	params := map[int]string{
		422: resources_core.FormatString(data.ResourceRealm),
		424: resources_core.FormatInt64(data.ResourceCPU),
		425: resources_core.FormatInt64(data.ResourceMemory),
		426: resources_core.FormatInt64(data.ResourceDisk),
		427: resources_core.FormatInt64(data.ResourceInstances),
		428: resources_core.FormatBool(data.NeedExternalAddressMaster),
		429: resources_core.FormatString(data.IpSpaceNameMaster),
		430: resources_core.FormatString(data.ExtBACKUPSCHEDULE),
		431: resources_core.FormatString(data.AppVersion),
		432: resources_core.FormatBool(data.AutoScale),
		433: resources_core.FormatInt64(data.AutoScalePercentage),
		434: resources_core.FormatInt64(data.AutoScaleTechWindow),
		435: resources_core.FormatInt64(data.AutoScaleQuotaGb),
		459: resources_core.FormatString(data.S3Uid),
	}

	id, err := resources_core.CreateResource(ctx, r.client, 115, resourceName, data.ResumeIfExists.ValueBool(), params)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	data.ID = types.StringValue(id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *MariadbResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *MariadbModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if data == nil {
		return
	}
	if r.client != nil && !data.ID.IsNull() && !data.ID.IsUnknown() {
		state, err := r.client.GetInstanceState(ctx, data.ID.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
		if state != nil {
			status := strings.ToLower(strings.TrimSpace(state.ExplainedStatus))
			if state.IsDeleted || status == "deleted" {
				resp.State.RemoveResource(ctx)
				return
			}
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *MariadbResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan MariadbModel
	var state MariadbModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	instanceID := state.ID
	if instanceID.IsNull() || instanceID.IsUnknown() {
		instanceID = plan.ID
	}
	if instanceID.IsNull() || instanceID.IsUnknown() {
		resp.Diagnostics.AddError("Client Error", "missing instance id for modify")
		return
	}

	params := map[int]string{
		436: resources_core.FormatInt64(plan.ResourceCPU),
		437: resources_core.FormatInt64(plan.ResourceMemory),
		438: resources_core.FormatInt64(plan.ResourceInstances),
		439: resources_core.FormatInt64(plan.ResourceDisk),
		440: resources_core.FormatBool(plan.NeedExternalAddressMaster),
		441: resources_core.FormatString(plan.IpSpaceNameMaster),
		442: resources_core.FormatString(plan.ExtBACKUPSCHEDULE),
		443: resources_core.FormatBool(plan.AutoScale),
		444: resources_core.FormatInt64(plan.AutoScalePercentage),
		445: resources_core.FormatInt64(plan.AutoScaleTechWindow),
		446: resources_core.FormatInt64(plan.AutoScaleQuotaGb),
	}

	if err := resources_core.UpdateResource(ctx, r.client, instanceID.ValueString(), params); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	plan.ID = instanceID
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *MariadbResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state *MariadbModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state == nil || state.ID.IsNull() || state.ID.IsUnknown() {
		return
	}

	if err := resources_core.DeleteResource(ctx, r.client, state.ID.ValueString(), state.DeleteMode.ValueString()); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}
}

func (r *MariadbResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*core.UniversalClient)
	if !ok {
		resp.Diagnostics.AddError("Error", "Wrong client type expected *core.UniversalClient")
		return
	}

	r.client = client
}

// format helpers live in resources_core/helpers.go
