package resources_gen

import (
	"context"
	"strings"

	"terraform-provider-nubes/internal/core"
	"terraform-provider-nubes/internal/resources_core"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Code generated by tools/gen. DO NOT EDIT.
// Service: postgres
// Service ID: 90

var _ resource.Resource = &PostgresResource{}
var _ resource.ResourceWithModifyPlan = &PostgresResource{}

type PostgresResource struct {
	client *core.UniversalClient
}

type PostgresModel struct {
	ID                        types.String `tfsdk:"id"`
	ResourceName              types.String `tfsdk:"resource_name"`
	S3Uid                     types.String `tfsdk:"s3_uid"`
	ResourceInstances         types.Int64  `tfsdk:"resource_instances"`
	ResourceMemory            types.Int64  `tfsdk:"resource_memory"`
	ResourceCPU               types.Int64  `tfsdk:"resource_c_p_u"`
	ResourceDisk              types.String `tfsdk:"resource_disk"`
	ResourceRealm             types.String `tfsdk:"resource_realm"`
	NeedExternalAddressMaster types.Bool   `tfsdk:"need_external_address_master"`
	NeedExternalAddressSlave  types.Bool   `tfsdk:"need_external_address_slave"`
	ExtBACKUPSCHEDULE         types.String `tfsdk:"ext__b_a_c_k_u_p__s_c_h_e_d_u_l_e"`
	ExtBACKUPNUMTORETAIN      types.Int64  `tfsdk:"ext__b_a_c_k_u_p__n_u_m__t_o__r_e_t_a_i_n"`
	AppVersion                types.String `tfsdk:"app_version"`
	JsonParameters            types.String `tfsdk:"json_parameters"`
	EnablePgPoolerMaster      types.Bool   `tfsdk:"enable_pg_pooler_master"`
	EnablePgPoolerSlave       types.Bool   `tfsdk:"enable_pg_pooler_slave"`
	AllowNoSSL                types.Bool   `tfsdk:"allow_no_s_s_l"`
	AutoScale                 types.Bool   `tfsdk:"auto_scale"`
	AutoScalePercentage       types.Int64  `tfsdk:"auto_scale_percentage"`
	AutoScaleTechWindow       types.Int64  `tfsdk:"auto_scale_tech_window"`
	IpSpaceNameMaster         types.String `tfsdk:"ip_space_name_master"`
	IpSpaceNameSlave          types.String `tfsdk:"ip_space_name_slave"`
	AutoScaleQuotaGb          types.String `tfsdk:"auto_scale_quota_gb"`
	DeleteMode                types.String `tfsdk:"delete_mode"`
	ResumeIfExists            types.Bool   `tfsdk:"resume_if_exists"`
}

func NewPostgresResource() resource.Resource {
	return &PostgresResource{}
}

func (r *PostgresResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_postgres"
}

func (r *PostgresResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id":            schema.StringAttribute{Computed: true},
		"resource_name": schema.StringAttribute{Required: true},
		"s3_uid": schema.StringAttribute{
			Required: true,
		},
		"resource_instances": schema.Int64Attribute{
			Required: true,
		},
		"resource_memory": schema.Int64Attribute{
			Required: true,
		},
		"resource_c_p_u": schema.Int64Attribute{
			Required: true,
		},
		"resource_disk": schema.StringAttribute{
			Required: true,
		},
		"resource_realm": schema.StringAttribute{
			Required: true,
		},
		"need_external_address_master": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(false),
		},
		"need_external_address_slave": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(false),
		},
		"ext__b_a_c_k_u_p__s_c_h_e_d_u_l_e": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("0 0 * * *"),
		},
		"ext__b_a_c_k_u_p__n_u_m__t_o__r_e_t_a_i_n": schema.Int64Attribute{
			Optional: true,
			Computed: true,
			Default:  int64default.StaticInt64(7),
		},
		"app_version": schema.StringAttribute{
			Required: true,
		},
		"json_parameters": schema.StringAttribute{
			Required: true,
		},
		"enable_pg_pooler_master": schema.BoolAttribute{
			Required: true,
		},
		"enable_pg_pooler_slave": schema.BoolAttribute{
			Required: true,
		},
		"allow_no_s_s_l": schema.BoolAttribute{
			Required: true,
		},
		"auto_scale": schema.BoolAttribute{
			Required: true,
		},
		"auto_scale_percentage": schema.Int64Attribute{
			Required: true,
		},
		"auto_scale_tech_window": schema.Int64Attribute{
			Required: true,
		},
		"ip_space_name_master": schema.StringAttribute{
			Optional: true,
		},
		"ip_space_name_slave": schema.StringAttribute{
			Optional: true,
		},
		"auto_scale_quota_gb": schema.StringAttribute{
			Required: true,
		},
		"delete_mode": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("state_only"),
		},
		"resume_if_exists": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(true),
		},
	}

	resp.Schema = schema.Schema{Attributes: attrs}
}

func (r *PostgresResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if r.client == nil {
		return
	}

	var config *PostgresModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if config == nil {
		return
	}

	var state *PostgresModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state != nil && !state.ID.IsNull() && !state.ID.IsUnknown() {
		return
	}

	if config.ResourceName.IsNull() || config.ResourceName.IsUnknown() {
		return
	}
	resumeIfExists := true
	if !config.ResumeIfExists.IsNull() && !config.ResumeIfExists.IsUnknown() {
		resumeIfExists = config.ResumeIfExists.ValueBool()
	}

	existing, err := r.client.FindInstanceByDisplayName(ctx, 90, config.ResourceName.ValueString())
	if err != nil || existing == nil {
		return
	}

	if !resumeIfExists {
		resp.Diagnostics.AddError(
			"RESOURCE WITH SAME NAME EXISTS",
			"A resource with the same resource_name already exists. Set resume_if_exists=true to adopt or choose a different name.",
		)
		return
	}

	status := strings.ToLower(existing.ExplainedStatus)
	if strings.Contains(status, "suspend") {
		resp.Diagnostics.AddWarning(
			"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
			"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
		)
		return
	}

	resp.Diagnostics.AddWarning(
		"RESOURCE WITH SAME NAME EXISTS",
		"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
	)
}

func (r *PostgresResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data PostgresModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resourceName := data.ResourceName.ValueString()
	if r.client != nil && !data.ResumeIfExists.IsNull() && !data.ResumeIfExists.IsUnknown() && data.ResumeIfExists.ValueBool() {
		existing, err := r.client.FindInstanceByDisplayName(ctx, 90, resourceName)
		if err == nil && existing != nil {
			status := strings.ToLower(existing.ExplainedStatus)
			if strings.Contains(status, "suspend") {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
					"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			} else {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS",
					"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			}
		}
	}

	params := map[int]string{
		23:  resources_core.FormatString(data.S3Uid),
		80:  resources_core.FormatInt64(data.ResourceInstances),
		81:  resources_core.FormatInt64(data.ResourceMemory),
		82:  resources_core.FormatInt64(data.ResourceCPU),
		83:  resources_core.FormatString(data.ResourceDisk),
		102: resources_core.FormatString(data.ResourceRealm),
		145: resources_core.FormatBool(data.NeedExternalAddressMaster),
		146: resources_core.FormatBool(data.NeedExternalAddressSlave),
		265: resources_core.FormatString(data.ExtBACKUPSCHEDULE),
		266: resources_core.FormatInt64(data.ExtBACKUPNUMTORETAIN),
		310: resources_core.FormatString(data.AppVersion),
		311: resources_core.FormatString(data.JsonParameters),
		312: resources_core.FormatBool(data.EnablePgPoolerMaster),
		313: resources_core.FormatBool(data.EnablePgPoolerSlave),
		314: resources_core.FormatBool(data.AllowNoSSL),
		329: resources_core.FormatBool(data.AutoScale),
		330: resources_core.FormatInt64(data.AutoScalePercentage),
		331: resources_core.FormatInt64(data.AutoScaleTechWindow),
		337: resources_core.FormatString(data.IpSpaceNameMaster),
		338: resources_core.FormatString(data.IpSpaceNameSlave),
		339: resources_core.FormatString(data.AutoScaleQuotaGb),
	}

	id, err := resources_core.CreateResource(ctx, r.client, 90, resourceName, data.ResumeIfExists.ValueBool(), params)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	data.ID = types.StringValue(id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *PostgresResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *PostgresModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if data == nil {
		return
	}
	if r.client != nil && !data.ID.IsNull() && !data.ID.IsUnknown() {
		state, err := r.client.GetInstanceState(ctx, data.ID.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
		if state != nil {
			status := strings.ToLower(strings.TrimSpace(state.ExplainedStatus))
			if state.IsDeleted || status == "deleted" {
				resp.State.RemoveResource(ctx)
				return
			}
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *PostgresResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan PostgresModel
	var state PostgresModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	instanceID := state.ID
	if instanceID.IsNull() || instanceID.IsUnknown() {
		instanceID = plan.ID
	}
	if instanceID.IsNull() || instanceID.IsUnknown() {
		resp.Diagnostics.AddError("Client Error", "missing instance id for modify")
		return
	}

	params := map[int]string{
		91:  resources_core.FormatInt64(plan.ResourceInstances),
		92:  resources_core.FormatInt64(plan.ResourceMemory),
		93:  resources_core.FormatInt64(plan.ResourceCPU),
		94:  resources_core.FormatString(plan.ResourceDisk),
		147: resources_core.FormatBool(plan.NeedExternalAddressMaster),
		148: resources_core.FormatBool(plan.NeedExternalAddressSlave),
		267: resources_core.FormatString(plan.ExtBACKUPSCHEDULE),
		268: resources_core.FormatInt64(plan.ExtBACKUPNUMTORETAIN),
		315: resources_core.FormatString(plan.AppVersion),
		316: resources_core.FormatString(plan.JsonParameters),
		317: resources_core.FormatBool(plan.EnablePgPoolerMaster),
		318: resources_core.FormatBool(plan.EnablePgPoolerSlave),
		319: resources_core.FormatBool(plan.AllowNoSSL),
		541: resources_core.FormatString(plan.IpSpaceNameMaster),
		542: resources_core.FormatString(plan.IpSpaceNameSlave),
	}

	if err := resources_core.UpdateResource(ctx, r.client, instanceID.ValueString(), params); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	plan.ID = instanceID
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *PostgresResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state *PostgresModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state == nil || state.ID.IsNull() || state.ID.IsUnknown() {
		return
	}

	if err := resources_core.DeleteResource(ctx, r.client, state.ID.ValueString(), state.DeleteMode.ValueString()); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}
}

func (r *PostgresResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*core.UniversalClient)
	if !ok {
		resp.Diagnostics.AddError("Error", "Wrong client type expected *core.UniversalClient")
		return
	}

	r.client = client
}

// format helpers live in resources_core/helpers.go
