package resources_gen

import "github.com/hashicorp/terraform-plugin-framework/resource"

// Code generated by tools/gen. DO NOT EDIT.
func AllResources() []func() resource.Resource {
	return []func() resource.Resource{
		NewGiteaComplexResource,
		NewDummyResource,
		NewFlaskResource,
		NewGiteaResource,
		NewHarborResource,
		NewKafkaResource,
		NewLuceeResource,
		NewMariadbResource,
		NewMongodbResource,
		NewNifiResource,
		NewNodejsResource,
		NewNoderedResource,
		NewPgadminResource,
		NewPostgresResource,
		NewRabbitmqResource,
		NewRedisResource,
		NewS3Resource,
		NewS3bucketResource,
		NewSupersetResource,
		NewVappResource,
		NewVcNsxtResource,
		NewVcVdcResource,
		NewVcVmV3Resource,
		NewVcexternalipResource,
	}
}
