package resources_gen

import (
	"context"
	"strings"

	"terraform-provider-nubes/internal/core"
	"terraform-provider-nubes/internal/resources_core"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Code generated by tools/gen. DO NOT EDIT.
// Service: s3
// Service ID: 12

var _ resource.Resource = &S3Resource{}
var _ resource.ResourceWithModifyPlan = &S3Resource{}

type S3Resource struct {
	client *core.UniversalClient
}

type S3Model struct {
	ID                  types.String `tfsdk:"id"`
	ResourceName        types.String `tfsdk:"resource_name"`
	ResourceRealm       types.String `tfsdk:"resource_realm"`
	DisplayName         types.String `tfsdk:"display_name"`
	MaxSizeGbPerUser    types.Int64  `tfsdk:"max_size_gb_per_user"`
	MaxObjectsPerBucket types.Int64  `tfsdk:"max_objects_per_bucket"`
	MaxBucketsPerUser   types.Int64  `tfsdk:"max_buckets_per_user"`
	DeleteMode          types.String `tfsdk:"delete_mode"`
	ResumeIfExists      types.Bool   `tfsdk:"resume_if_exists"`
}

func NewS3Resource() resource.Resource {
	return &S3Resource{}
}

func (r *S3Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_s3"
}

func (r *S3Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id":            schema.StringAttribute{Computed: true},
		"resource_name": schema.StringAttribute{Required: true},
		"resource_realm": schema.StringAttribute{
			Required: true,
		},
		"display_name": schema.StringAttribute{
			Required: true,
		},
		"max_size_gb_per_user": schema.Int64Attribute{
			Optional: true,
		},
		"max_objects_per_bucket": schema.Int64Attribute{
			Optional: true,
		},
		"max_buckets_per_user": schema.Int64Attribute{
			Optional: true,
		},
		"delete_mode": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("state_only"),
		},
		"resume_if_exists": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(true),
		},
	}

	resp.Schema = schema.Schema{Attributes: attrs}
}

func (r *S3Resource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if r.client == nil {
		return
	}

	var config *S3Model
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if config == nil {
		return
	}

	var state *S3Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state != nil && !state.ID.IsNull() && !state.ID.IsUnknown() {
		return
	}

	if config.ResourceName.IsNull() || config.ResourceName.IsUnknown() {
		return
	}
	resumeIfExists := true
	if !config.ResumeIfExists.IsNull() && !config.ResumeIfExists.IsUnknown() {
		resumeIfExists = config.ResumeIfExists.ValueBool()
	}

	existing, err := r.client.FindInstanceByDisplayName(ctx, 12, config.ResourceName.ValueString())
	if err != nil || existing == nil {
		return
	}

	if !resumeIfExists {
		resp.Diagnostics.AddError(
			"RESOURCE WITH SAME NAME EXISTS",
			"A resource with the same resource_name already exists. Set resume_if_exists=true to adopt or choose a different name.",
		)
		return
	}

	status := strings.ToLower(existing.ExplainedStatus)
	if strings.Contains(status, "suspend") {
		resp.Diagnostics.AddWarning(
			"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
			"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
		)
		return
	}

	resp.Diagnostics.AddWarning(
		"RESOURCE WITH SAME NAME EXISTS",
		"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
	)
}

func (r *S3Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data S3Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resourceName := data.ResourceName.ValueString()
	if r.client != nil && !data.ResumeIfExists.IsNull() && !data.ResumeIfExists.IsUnknown() && data.ResumeIfExists.ValueBool() {
		existing, err := r.client.FindInstanceByDisplayName(ctx, 12, resourceName)
		if err == nil && existing != nil {
			status := strings.ToLower(existing.ExplainedStatus)
			if strings.Contains(status, "suspend") {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
					"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			} else {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS",
					"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			}
		}
	}

	params := map[int]string{
		163: resources_core.FormatString(data.ResourceRealm),
		320: resources_core.FormatString(data.DisplayName),
	}

	id, err := resources_core.CreateResource(ctx, r.client, 12, resourceName, data.ResumeIfExists.ValueBool(), params)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	data.ID = types.StringValue(id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *S3Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *S3Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if data == nil {
		return
	}
	if r.client != nil && !data.ID.IsNull() && !data.ID.IsUnknown() {
		state, err := r.client.GetInstanceState(ctx, data.ID.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
		if state != nil {
			status := strings.ToLower(strings.TrimSpace(state.ExplainedStatus))
			if state.IsDeleted || status == "deleted" {
				resp.State.RemoveResource(ctx)
				return
			}
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *S3Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan S3Model
	var state S3Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	instanceID := state.ID
	if instanceID.IsNull() || instanceID.IsUnknown() {
		instanceID = plan.ID
	}
	if instanceID.IsNull() || instanceID.IsUnknown() {
		resp.Diagnostics.AddError("Client Error", "missing instance id for modify")
		return
	}

	params := map[int]string{
		50: resources_core.FormatInt64(plan.MaxSizeGbPerUser),
		51: resources_core.FormatInt64(plan.MaxObjectsPerBucket),
		52: resources_core.FormatInt64(plan.MaxBucketsPerUser),
	}

	if err := resources_core.UpdateResource(ctx, r.client, instanceID.ValueString(), params); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	plan.ID = instanceID
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *S3Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state *S3Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state == nil || state.ID.IsNull() || state.ID.IsUnknown() {
		return
	}

	if err := resources_core.DeleteResource(ctx, r.client, state.ID.ValueString(), state.DeleteMode.ValueString()); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}
}

func (r *S3Resource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*core.UniversalClient)
	if !ok {
		resp.Diagnostics.AddError("Error", "Wrong client type expected *core.UniversalClient")
		return
	}

	r.client = client
}

// format helpers live in resources_core/helpers.go
