package resources_gen

import (
	"context"
	"strings"

	"terraform-provider-nubes/internal/core"
	"terraform-provider-nubes/internal/resources_core"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Code generated by tools/gen. DO NOT EDIT.
// Service: vc_vm_v3
// Service ID: 28

var _ resource.Resource = &VcVmV3Resource{}
var _ resource.ResourceWithModifyPlan = &VcVmV3Resource{}

type VcVmV3Resource struct {
	client *core.UniversalClient
}

type VcVmV3Model struct {
	ID                    types.String `tfsdk:"id"`
	ResourceName          types.String `tfsdk:"resource_name"`
	VappUid               types.String `tfsdk:"vapp_uid"`
	VmName                types.String `tfsdk:"vm_name"`
	VmCpu                 types.Int64  `tfsdk:"vm_cpu"`
	VmRam                 types.Int64  `tfsdk:"vm_ram"`
	VmDisk                types.Int64  `tfsdk:"vm_disk"`
	IpSpaceName           types.String `tfsdk:"ip_space_name"`
	AccessIpList          types.String `tfsdk:"access_ip_list"`
	ImageVm               types.String `tfsdk:"image_vm"`
	CloudInit             types.String `tfsdk:"cloud_init"`
	UserLogin             types.String `tfsdk:"user_login"`
	UserPublicKey         types.String `tfsdk:"user_public_key"`
	AccessPortList        types.String `tfsdk:"access_port_list"`
	NeedAddZabbixTemplate types.Bool   `tfsdk:"need_add_zabbix_template"`
	DeleteMode            types.String `tfsdk:"delete_mode"`
	ResumeIfExists        types.Bool   `tfsdk:"resume_if_exists"`
}

func NewVcVmV3Resource() resource.Resource {
	return &VcVmV3Resource{}
}

func (r *VcVmV3Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vc_vm_v3"
}

func (r *VcVmV3Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id":            schema.StringAttribute{Computed: true},
		"resource_name": schema.StringAttribute{Required: true},
		"vapp_uid": schema.StringAttribute{
			Required: true,
		},
		"vm_name": schema.StringAttribute{
			Required: true,
		},
		"vm_cpu": schema.Int64Attribute{
			Required: true,
		},
		"vm_ram": schema.Int64Attribute{
			Required: true,
		},
		"vm_disk": schema.Int64Attribute{
			Optional: true,
		},
		"ip_space_name": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("no-needed"),
		},
		"access_ip_list": schema.StringAttribute{
			Optional: true,
		},
		"image_vm": schema.StringAttribute{
			Required: true,
		},
		"cloud_init": schema.StringAttribute{
			Optional: true,
		},
		"user_login": schema.StringAttribute{
			Required: true,
		},
		"user_public_key": schema.StringAttribute{
			Required: true,
		},
		"access_port_list": schema.StringAttribute{
			Required: true,
		},
		"need_add_zabbix_template": schema.BoolAttribute{
			Required: true,
		},
		"delete_mode": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("state_only"),
		},
		"resume_if_exists": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(true),
		},
	}

	resp.Schema = schema.Schema{Attributes: attrs}
}

func (r *VcVmV3Resource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if r.client == nil {
		return
	}

	var config *VcVmV3Model
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if config == nil {
		return
	}

	var state *VcVmV3Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state != nil && !state.ID.IsNull() && !state.ID.IsUnknown() {
		return
	}

	if config.ResourceName.IsNull() || config.ResourceName.IsUnknown() {
		return
	}
	resumeIfExists := true
	if !config.ResumeIfExists.IsNull() && !config.ResumeIfExists.IsUnknown() {
		resumeIfExists = config.ResumeIfExists.ValueBool()
	}

	existing, err := r.client.FindInstanceByDisplayName(ctx, 28, config.ResourceName.ValueString())
	if err != nil || existing == nil {
		return
	}

	if !resumeIfExists {
		resp.Diagnostics.AddError(
			"RESOURCE WITH SAME NAME EXISTS",
			"A resource with the same resource_name already exists. Set resume_if_exists=true to adopt or choose a different name.",
		)
		return
	}

	status := strings.ToLower(existing.ExplainedStatus)
	if strings.Contains(status, "suspend") {
		resp.Diagnostics.AddWarning(
			"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
			"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
		)
		return
	}

	resp.Diagnostics.AddWarning(
		"RESOURCE WITH SAME NAME EXISTS",
		"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
	)
}

func (r *VcVmV3Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data VcVmV3Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resourceName := data.ResourceName.ValueString()
	if r.client != nil && !data.ResumeIfExists.IsNull() && !data.ResumeIfExists.IsUnknown() && data.ResumeIfExists.ValueBool() {
		existing, err := r.client.FindInstanceByDisplayName(ctx, 28, resourceName)
		if err == nil && existing != nil {
			status := strings.ToLower(existing.ExplainedStatus)
			if strings.Contains(status, "suspend") {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
					"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			} else {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS",
					"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			}
		}
	}

	params := map[int]string{
		407: resources_core.FormatString(data.VappUid),
		408: resources_core.FormatString(data.VmName),
		409: resources_core.FormatInt64(data.VmCpu),
		410: resources_core.FormatInt64(data.VmRam),
		411: resources_core.FormatInt64(data.VmDisk),
		412: resources_core.FormatString(data.IpSpaceName),
		413: resources_core.FormatString(data.AccessIpList),
		414: resources_core.FormatString(data.ImageVm),
		415: resources_core.FormatString(data.CloudInit),
		416: resources_core.FormatString(data.UserLogin),
		417: resources_core.FormatString(data.UserPublicKey),
		448: resources_core.FormatString(data.AccessPortList),
		449: resources_core.FormatBool(data.NeedAddZabbixTemplate),
	}

	id, err := resources_core.CreateResource(ctx, r.client, 28, resourceName, data.ResumeIfExists.ValueBool(), params)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	data.ID = types.StringValue(id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *VcVmV3Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *VcVmV3Model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if data == nil {
		return
	}
	if r.client != nil && !data.ID.IsNull() && !data.ID.IsUnknown() {
		state, err := r.client.GetInstanceState(ctx, data.ID.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
		if state != nil {
			status := strings.ToLower(strings.TrimSpace(state.ExplainedStatus))
			if state.IsDeleted || status == "deleted" {
				resp.State.RemoveResource(ctx)
				return
			}
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *VcVmV3Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan VcVmV3Model
	var state VcVmV3Model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	instanceID := state.ID
	if instanceID.IsNull() || instanceID.IsUnknown() {
		instanceID = plan.ID
	}
	if instanceID.IsNull() || instanceID.IsUnknown() {
		resp.Diagnostics.AddError("Client Error", "missing instance id for modify")
		return
	}

	params := map[int]string{
		493: resources_core.FormatInt64(plan.VmCpu),
		494: resources_core.FormatInt64(plan.VmRam),
		495: resources_core.FormatInt64(plan.VmDisk),
		496: resources_core.FormatString(plan.IpSpaceName),
		497: resources_core.FormatString(plan.AccessIpList),
		498: resources_core.FormatString(plan.AccessPortList),
		499: resources_core.FormatBool(plan.NeedAddZabbixTemplate),
	}

	if err := resources_core.UpdateResource(ctx, r.client, instanceID.ValueString(), params); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	plan.ID = instanceID
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *VcVmV3Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state *VcVmV3Model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state == nil || state.ID.IsNull() || state.ID.IsUnknown() {
		return
	}

	if err := resources_core.DeleteResource(ctx, r.client, state.ID.ValueString(), state.DeleteMode.ValueString()); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}
}

func (r *VcVmV3Resource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*core.UniversalClient)
	if !ok {
		resp.Diagnostics.AddError("Error", "Wrong client type expected *core.UniversalClient")
		return
	}

	r.client = client
}

// format helpers live in resources_core/helpers.go
