package resources_gen

import (
	"context"
	"strings"

	"terraform-provider-nubes/internal/core"
	"terraform-provider-nubes/internal/resources_core"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Code generated by tools/gen. DO NOT EDIT.
// Service: vcexternalip
// Service ID: 25

var _ resource.Resource = &VcexternalipResource{}
var _ resource.ResourceWithModifyPlan = &VcexternalipResource{}

type VcexternalipResource struct {
	client *core.UniversalClient
}

type VcexternalipModel struct {
	ID                        types.String `tfsdk:"id"`
	ResourceName              types.String `tfsdk:"resource_name"`
	ServiceUid                types.String `tfsdk:"service_uid"`
	DnatCreate                types.Bool   `tfsdk:"dnat_create"`
	InternalPortAccess        types.String `tfsdk:"internal_port_access"`
	SnatCreate                types.Bool   `tfsdk:"snat_create"`
	InternalAddrAccess        types.String `tfsdk:"internal_addr_access"`
	FromServiceNamespace      types.String `tfsdk:"from_service_namespace"`
	FromServiceCloudEdgeName  types.String `tfsdk:"from_service_cloud_edge_name"`
	FromServiceCloudVdcName   types.String `tfsdk:"from_service_cloud_vdc_name"`
	FromServiceCloudOrgName   types.String `tfsdk:"from_service_cloud_org_name"`
	FromServiceCloudVmwareUrl types.String `tfsdk:"from_service_cloud_vmware_url"`
	IpSpaceName               types.String `tfsdk:"ip_space_name"`
	ResourceRealm             types.String `tfsdk:"resource_realm"`
	FromServiceCloudEdgeScope types.String `tfsdk:"from_service_cloud_edge_scope"`
	FromServiceVdcGroupName   types.String `tfsdk:"from_service_vdc_group_name"`
	DeleteMode                types.String `tfsdk:"delete_mode"`
	ResumeIfExists            types.Bool   `tfsdk:"resume_if_exists"`
}

func NewVcexternalipResource() resource.Resource {
	return &VcexternalipResource{}
}

func (r *VcexternalipResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_vcexternalip"
}

func (r *VcexternalipResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id":            schema.StringAttribute{Computed: true},
		"resource_name": schema.StringAttribute{Required: true},
		"service_uid": schema.StringAttribute{
			Required: true,
		},
		"dnat_create": schema.BoolAttribute{
			Required: true,
		},
		"internal_port_access": schema.StringAttribute{
			Required: true,
		},
		"snat_create": schema.BoolAttribute{
			Optional: true,
		},
		"internal_addr_access": schema.StringAttribute{
			Required: true,
		},
		"from_service_namespace": schema.StringAttribute{
			Required: true,
		},
		"from_service_cloud_edge_name": schema.StringAttribute{
			Optional: true,
		},
		"from_service_cloud_vdc_name": schema.StringAttribute{
			Optional: true,
		},
		"from_service_cloud_org_name": schema.StringAttribute{
			Optional: true,
		},
		"from_service_cloud_vmware_url": schema.StringAttribute{
			Optional: true,
		},
		"ip_space_name": schema.StringAttribute{
			Required: true,
		},
		"resource_realm": schema.StringAttribute{
			Required: true,
		},
		"from_service_cloud_edge_scope": schema.StringAttribute{
			Optional: true,
		},
		"from_service_vdc_group_name": schema.StringAttribute{
			Optional: true,
		},
		"delete_mode": schema.StringAttribute{
			Optional: true,
			Computed: true,
			Default:  stringdefault.StaticString("state_only"),
		},
		"resume_if_exists": schema.BoolAttribute{
			Optional: true,
			Computed: true,
			Default:  booldefault.StaticBool(true),
		},
	}

	resp.Schema = schema.Schema{Attributes: attrs}
}

func (r *VcexternalipResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if r.client == nil {
		return
	}

	var config *VcexternalipModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if config == nil {
		return
	}

	var state *VcexternalipModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state != nil && !state.ID.IsNull() && !state.ID.IsUnknown() {
		return
	}

	if config.ResourceName.IsNull() || config.ResourceName.IsUnknown() {
		return
	}
	resumeIfExists := true
	if !config.ResumeIfExists.IsNull() && !config.ResumeIfExists.IsUnknown() {
		resumeIfExists = config.ResumeIfExists.ValueBool()
	}

	existing, err := r.client.FindInstanceByDisplayName(ctx, 25, config.ResourceName.ValueString())
	if err != nil || existing == nil {
		return
	}

	if !resumeIfExists {
		resp.Diagnostics.AddError(
			"RESOURCE WITH SAME NAME EXISTS",
			"A resource with the same resource_name already exists. Set resume_if_exists=true to adopt or choose a different name.",
		)
		return
	}

	status := strings.ToLower(existing.ExplainedStatus)
	if strings.Contains(status, "suspend") {
		resp.Diagnostics.AddWarning(
			"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
			"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
		)
		return
	}

	resp.Diagnostics.AddWarning(
		"RESOURCE WITH SAME NAME EXISTS",
		"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
	)
}

func (r *VcexternalipResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data VcexternalipModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resourceName := data.ResourceName.ValueString()
	if r.client != nil && !data.ResumeIfExists.IsNull() && !data.ResumeIfExists.IsUnknown() && data.ResumeIfExists.ValueBool() {
		existing, err := r.client.FindInstanceByDisplayName(ctx, 25, resourceName)
		if err == nil && existing != nil {
			status := strings.ToLower(existing.ExplainedStatus)
			if strings.Contains(status, "suspend") {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS (SUSPENDED)",
					"An existing resource with the same resource_name was found and is suspended. With resume_if_exists=true it will be resumed and adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			} else {
				resp.Diagnostics.AddWarning(
					"RESOURCE WITH SAME NAME EXISTS",
					"An existing resource with the same resource_name was found. With resume_if_exists=true it will be adopted without applying new parameters. Run plan/apply again with changes to perform modify.",
				)
			}
		}
	}

	params := map[int]string{
		140: resources_core.FormatString(data.ServiceUid),
		141: resources_core.FormatBool(data.DnatCreate),
		142: resources_core.FormatString(data.InternalPortAccess),
		143: resources_core.FormatBool(data.SnatCreate),
		144: resources_core.FormatString(data.InternalAddrAccess),
		324: resources_core.FormatString(data.FromServiceNamespace),
		325: resources_core.FormatString(data.FromServiceCloudEdgeName),
		326: resources_core.FormatString(data.FromServiceCloudVdcName),
		327: resources_core.FormatString(data.FromServiceCloudOrgName),
		328: resources_core.FormatString(data.FromServiceCloudVmwareUrl),
		336: resources_core.FormatString(data.IpSpaceName),
		488: resources_core.FormatString(data.ResourceRealm),
		624: resources_core.FormatString(data.FromServiceCloudEdgeScope),
		626: resources_core.FormatString(data.FromServiceVdcGroupName),
	}

	id, err := resources_core.CreateResource(ctx, r.client, 25, resourceName, data.ResumeIfExists.ValueBool(), params)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	data.ID = types.StringValue(id)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *VcexternalipResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *VcexternalipModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if data == nil {
		return
	}
	if r.client != nil && !data.ID.IsNull() && !data.ID.IsUnknown() {
		state, err := r.client.GetInstanceState(ctx, data.ID.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Client Error", err.Error())
			return
		}
		if state != nil {
			status := strings.ToLower(strings.TrimSpace(state.ExplainedStatus))
			if state.IsDeleted || status == "deleted" {
				resp.State.RemoveResource(ctx)
				return
			}
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, data)...)
}

func (r *VcexternalipResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan VcexternalipModel
	var state VcexternalipModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	instanceID := state.ID
	if instanceID.IsNull() || instanceID.IsUnknown() {
		instanceID = plan.ID
	}
	if instanceID.IsNull() || instanceID.IsUnknown() {
		resp.Diagnostics.AddError("Client Error", "missing instance id for modify")
		return
	}

	params := map[int]string{
		627: resources_core.FormatString(plan.ServiceUid),
		628: resources_core.FormatString(plan.IpSpaceName),
		629: resources_core.FormatBool(plan.DnatCreate),
		630: resources_core.FormatBool(plan.SnatCreate),
		631: resources_core.FormatString(plan.InternalPortAccess),
		632: resources_core.FormatString(plan.InternalAddrAccess),
	}

	if err := resources_core.UpdateResource(ctx, r.client, instanceID.ValueString(), params); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	plan.ID = instanceID
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *VcexternalipResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state *VcexternalipModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if state == nil || state.ID.IsNull() || state.ID.IsUnknown() {
		return
	}

	if err := resources_core.DeleteResource(ctx, r.client, state.ID.ValueString(), state.DeleteMode.ValueString()); err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}
}

func (r *VcexternalipResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*core.UniversalClient)
	if !ok {
		resp.Diagnostics.AddError("Error", "Wrong client type expected *core.UniversalClient")
		return
	}

	r.client = client
}

// format helpers live in resources_core/helpers.go
