apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrakNDQXVLZ0F3SUJBZ0lRT00yclVySHVwSnY2eHlSL2pWWi9ZakFOQmdrcWhraUc5dzBCQVEwRkFEQVgKTVJVd0V3WURWUVFERXd4T2FVWnBMVzFVVEZNdFEwRXdIaGNOTWpZd01UQTFNRFl4TWpBeldoY05Nell3TVRBegpNRFl4TWpBeldqQVhNUlV3RXdZRFZRUURFd3hPYVVacExXMVVURk10UTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDbENmdTQ4bkErZCtSUldXaGc2anUrM0lPMnhyN3Jqb2ZZMXNjay94aGIKaDFMdXIvZDFZekhQdUFJVWswdHl0V1VwbndmaDAwaEROdkhORUVXV3dyeW9HL0E2dTNJdlVQeW9uajRVZm1EaQpKT2ZndnFsYUFKOEJmbEVGRlpxSTc3SWJJOUpTblVoWngyYWVvRUlMZGVYTjhUN2diT3lsZmRKWTMzNVUrTGV5CnVJNnh4cFF0cWlQSWdrdlp3VjcyU09iS3hWcFFpYytCNHpnTDNWUVpnUDVzV0Z0cS80d3Y2Y3E3VE1LdWhWUjcKNHhveFFPQ1U4KzFqa292dTl3Z0l4bzhHNjFBOE11YlVGcXNneWRyUnArVndYYWpxNGsyREtiYXFkaDVRSlVvVwppeG1mQ3RlMTZYbzB2aGh3cTl3NS9BcFJUNmQ2ZERTY2ZQUFpWbmJESzhHMXVhNE50Y2hTOVE3T0l4TEVYeDhTClNnMjcraC9jTExHQlBxUDM1bE5LVGQ0RjhjQ2ZuY1ZQbjdhWnRNMjNkeWprWDB6Qk02OE1RbFA0bnBZUE0wemoKZzdVTUY4cWl4bVUrRU9ncng4S1NWNFcxQ3BqenczM2h2ZXlHYndvSUVya3VhenAwelpCcEF2Wm5UVUZtQlliaApSVGxiUXlpQjR0Sks1WlByUmJwb044UjhaM1AvRU93eDB1NkRjZUhqV1NxUTArMmJHUDI4ZGF1alhPZHdUR3Z0CnVMTFJVcnVKQnFSMXRtQkdhS2JTaXNUVUYyRVNQeHM4Sll1T0lSMGc3TENmWXoxUTN6M0lmR2NmS0dHdlVHc3AKY09KQUJGSmtrcWdiMnFkQzRNa3VaQXI0RklKR21sWXpyelU0NXlKcUlZa0poNXpieVJDaVRkRDJkeTA1Yzg4SAoyd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WCkhRNEVGZ1FVZkl3N2xXY2k3emZ3SWFHNngxVlhXMHZTZ0Q0d0RRWUpLb1pJaHZjTkFRRU5CUUFEZ2dJQkFFUEIKVkxGaTFva3lpMkdaeXM0TkVKaVo1MjhWSTgwTkFaZmpYazdyM2RIMEkzUVdsS0tJSk1WazRHU1RjWHBNcTNPTwpra0RyZ2szdTNkcloySlRiSXM4VmZteHQzL204YjVGNlBRN0Zzc1BhWlF5Mmx1a05KRlEyaHVtaDBiY08zK0RICmU2WHN4aE1samhQNkVEZWxYdy9nQS82WDNjdDhuM2U3aEIwTzdEZ0VRdThZNHFYMEw0dVY4U3ZvVmFQVkdHUjIKZDd3VElHQ1pjNitLOXJDeHNMTVQ2dFdxOFp4cGtFMHZzLzZEZ0FvUDNqanBUMURBUEpkZVFleFhaMUtlb043ZAo4ZWhCY2VTWXFyWWx4MzhPRHlVT1VONkwxT0ZPeTRocHYrWUppbHNMSjVpSGVLQ1dOSG9NaHVzWTlWM0JtTllqCllXbkwxc1NwaFlvN3ExTVdyUHdEMHM1STc5Z29QbXFBRUlJK1ZCcmhhaHhLTVFJMGpjYklNQXdrVW9CYXBjNDUKQ091cTFVWGRFeXIvTzdmRnBZOVdnQWtsYjJVSFpkQmVIVkFPbng0eTg2T0g4ZXptS1dTYnlaMUR5NEt4NmIwRgpZclFmZ1hCdi8xNXREeExQYytwdlp6UE1DWkcrcFRqL0ZnTUZNMzdNTG0vSHNsTDJHdGcyTjlRZzF1ei9vcG5KClBDNHpHZmgveGpQQUc5R1QrL2dQbXBjZFNGSEk0TmlCdG5HN3FTSDlXZHRXOEsvbnBFaEhkWmdGOVRRMFZ2U24KMnFvM0xWZTFlKzlYbytyekdtb0xPdlphaHEvNE1JRmI3bnVxdVZSK2I2ZmM3ZDR6Z1JiTWVVejFiOVQxSFdrWgprZzBUcHBRazR5UE5iMnBwcWxGYkMvZUV1ZWszcGpoM1QxaTN4eWlaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrakNDQXVLZ0F3SUJBZ0lRT00yclVySHVwSnY2eHlSL2pWWi9ZakFOQmdrcWhraUc5dzBCQVEwRkFEQVgKTVJVd0V3WURWUVFERXd4T2FVWnBMVzFVVEZNdFEwRXdIaGNOTWpZd01UQTFNRFl4TWpBeldoY05Nell3TVRBegpNRFl4TWpBeldqQVhNUlV3RXdZRFZRUURFd3hPYVVacExXMVVURk10UTBFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDbENmdTQ4bkErZCtSUldXaGc2anUrM0lPMnhyN3Jqb2ZZMXNjay94aGIKaDFMdXIvZDFZekhQdUFJVWswdHl0V1VwbndmaDAwaEROdkhORUVXV3dyeW9HL0E2dTNJdlVQeW9uajRVZm1EaQpKT2ZndnFsYUFKOEJmbEVGRlpxSTc3SWJJOUpTblVoWngyYWVvRUlMZGVYTjhUN2diT3lsZmRKWTMzNVUrTGV5CnVJNnh4cFF0cWlQSWdrdlp3VjcyU09iS3hWcFFpYytCNHpnTDNWUVpnUDVzV0Z0cS80d3Y2Y3E3VE1LdWhWUjcKNHhveFFPQ1U4KzFqa292dTl3Z0l4bzhHNjFBOE11YlVGcXNneWRyUnArVndYYWpxNGsyREtiYXFkaDVRSlVvVwppeG1mQ3RlMTZYbzB2aGh3cTl3NS9BcFJUNmQ2ZERTY2ZQUFpWbmJESzhHMXVhNE50Y2hTOVE3T0l4TEVYeDhTClNnMjcraC9jTExHQlBxUDM1bE5LVGQ0RjhjQ2ZuY1ZQbjdhWnRNMjNkeWprWDB6Qk02OE1RbFA0bnBZUE0wemoKZzdVTUY4cWl4bVUrRU9ncng4S1NWNFcxQ3BqenczM2h2ZXlHYndvSUVya3VhenAwelpCcEF2Wm5UVUZtQlliaApSVGxiUXlpQjR0Sks1WlByUmJwb044UjhaM1AvRU93eDB1NkRjZUhqV1NxUTArMmJHUDI4ZGF1alhPZHdUR3Z0CnVMTFJVcnVKQnFSMXRtQkdhS2JTaXNUVUYyRVNQeHM4Sll1T0lSMGc3TENmWXoxUTN6M0lmR2NmS0dHdlVHc3AKY09KQUJGSmtrcWdiMnFkQzRNa3VaQXI0RklKR21sWXpyelU0NXlKcUlZa0poNXpieVJDaVRkRDJkeTA1Yzg4SAoyd0lEQVFBQm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WCkhRNEVGZ1FVZkl3N2xXY2k3emZ3SWFHNngxVlhXMHZTZ0Q0d0RRWUpLb1pJaHZjTkFRRU5CUUFEZ2dJQkFFUEIKVkxGaTFva3lpMkdaeXM0TkVKaVo1MjhWSTgwTkFaZmpYazdyM2RIMEkzUVdsS0tJSk1WazRHU1RjWHBNcTNPTwpra0RyZ2szdTNkcloySlRiSXM4VmZteHQzL204YjVGNlBRN0Zzc1BhWlF5Mmx1a05KRlEyaHVtaDBiY08zK0RICmU2WHN4aE1samhQNkVEZWxYdy9nQS82WDNjdDhuM2U3aEIwTzdEZ0VRdThZNHFYMEw0dVY4U3ZvVmFQVkdHUjIKZDd3VElHQ1pjNitLOXJDeHNMTVQ2dFdxOFp4cGtFMHZzLzZEZ0FvUDNqanBUMURBUEpkZVFleFhaMUtlb043ZAo4ZWhCY2VTWXFyWWx4MzhPRHlVT1VONkwxT0ZPeTRocHYrWUppbHNMSjVpSGVLQ1dOSG9NaHVzWTlWM0JtTllqCllXbkwxc1NwaFlvN3ExTVdyUHdEMHM1STc5Z29QbXFBRUlJK1ZCcmhhaHhLTVFJMGpjYklNQXdrVW9CYXBjNDUKQ091cTFVWGRFeXIvTzdmRnBZOVdnQWtsYjJVSFpkQmVIVkFPbng0eTg2T0g4ZXptS1dTYnlaMUR5NEt4NmIwRgpZclFmZ1hCdi8xNXREeExQYytwdlp6UE1DWkcrcFRqL0ZnTUZNMzdNTG0vSHNsTDJHdGcyTjlRZzF1ei9vcG5KClBDNHpHZmgveGpQQUc5R1QrL2dQbXBjZFNGSEk0TmlCdG5HN3FTSDlXZHRXOEsvbnBFaEhkWmdGOVRRMFZ2U24KMnFvM0xWZTFlKzlYbytyekdtb0xPdlphaHEvNE1JRmI3bnVxdVZSK2I2ZmM3ZDR6Z1JiTWVVejFiOVQxSFdrWgprZzBUcHBRazR5UE5iMnBwcWxGYkMvZUV1ZWszcGpoM1QxaTN4eWlaCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBcFFuN3VQSndQbmZrVVZsb1lPbzd2dHlEdHNhKzY0NkgyTmJISlA4WVc0ZFM3cS8zCmRXTXh6N2dDRkpOTGNyVmxLWjhINGROSVF6Ynh6UkJGbHNLOHFCdndPcnR5TDFEOHFKNCtGSDVnNGlUbjRMNnAKV2dDZkFYNVJCUldhaU8reUd5UFNVcDFJV2NkbW5xQkNDM1hsemZFKzRHenNwWDNTV045K1ZQaTNzcmlPc2NhVQpMYW9qeUlKTDJjRmU5a2pteXNWYVVJblBnZU00QzkxVUdZRCtiRmhiYXYrTUwrbkt1MHpDcm9WVWUrTWFNVURnCmxQUHRZNUtMN3ZjSUNNYVBCdXRRUERMbTFCYXJJTW5hMGFmbGNGMm82dUpOZ3ltMnFuWWVVQ1ZLRm9zWm53clgKdGVsNk5MNFljS3ZjT2Z3S1VVK25lblEwbkh6ejJWWjJ3eXZCdGJtdURiWElVdlVPemlNU3hGOGZFa29OdS9vZgozQ3l4Z1Q2ajkrWlRTazNlQmZIQW41M0ZUNSsybWJUTnQzY281RjlNd1RPdkRFSlQrSjZXRHpOTTQ0TzFEQmZLCm9zWmxQaERvSzhmQ2tsZUZ0UXFZODhOOTRiM3NobThLQ0JLNUxtczZkTTJRYVFMMlowMUJaZ1dHNFVVNVcwTW8KZ2VMU1N1V1Q2MFc2YURmRWZHZHoveERzTWRMdWczSGg0MWtxa05QdG14ajl2SFdybzF6bmNFeHI3Yml5MFZLNwppUWFrZGJaZ1JtaW0wb3JFMUJkaEVqOGJQQ1dMamlFZElPeXduMk05VU44OXlIeG5IeWhocjFCcktYRGlRQVJTClpKS29HOXFuUXVESkxtUUsrQlNDUnBwV002ODFPT2NpYWlHSkNZZWMyOGtRb2szUTluY3RPWFBQQjlzQ0F3RUEKQVFLQ0FnQXhNdjJ3ajgxNFFlTjFnTkxGK1czZ0l2cTg5UmliUGowdkhpLzF6bm9qWnY4Skdyb0phNDNBMzVqMwpLMFhWcDAvR0RadWE3WkpnUHpQc0xzcWYrK09qdGRoeW1jaWJaR2c5bUJibm94a2NzV1hTc09QcGFiLzlBUHdFCktRR05pdThzZWd4TUJvazRBbUtNTFRnakZIMXlYRldqTDdXSVRDNzF3WUoyc0VLSzY4dldJVjJ4RTBSaGxMNHAKNXlSNUJSaVFJQzhoVFVQbjg2V1VtK0ZqVFBvTHNIZG9PVkJBUkZEa2J5aW1RQ2NFVzVwR1RwSGt0YWJ5QlJEawpKdzVsRjFReCt0cExaOTA2SXB2WFJYV1BCSjg0VlNOekNnMlRhVThFRi94SFppWmsvQWlpU2VndVdiRE5vbEhFCjNPYmsva2JSSUk3THlYS1pxQUpGcXlueVdzdis5dFcvcWVNZFdCMmMrUFY5TjJOM2dwK1hvdjRKN01NL1d3ZXQKRmJycmE2b3hycnpta2xmM3ZRT3ZUVVBkazBacDZkbDBmQlRHTzNMemR2UER5N01DaUgzb0JJQVJXaU5tOHBZWgp1RVN2eURDcmQycCtCelRya3ZJeWMzYllENjAvZFNlRkRRclNHMTVJOWpRemV4R3FLdVZQRnZBeWJmSEVNRHFUCjlLb2JTeG9jWWJ4Ym5GQnYrQVdtUjdpaTM5czArcVprbzNnWmNVcmtnOEZUa3VRT0gzbGcwNlNxalBnMWNvVzYKMVVNNVFlYUtZSzZ1WXVuVk9uL2xPdyt1TlBzT3RHM25sOUNEZDBHWDA3eVFVZnk1Qm1YeTB1aXRMd0xzTGk2awplREY4N0lzaFJ0TzAzTHNkV1p4U01JWXJpZ05QNTUveUJOT2M2YlpBcEVyWEszeWQ0UUtDQVFFQXdSY2FsZ2g1Ckp0T0I2UTRhcUVVR0FXbnpBcGFkSU1tMHpWa2sxQmkvUG5lc1JVVHIxSEVwK3J4TEVoZW5wMGs3VUFkbm9ZOTUKSXZRSXVvVm9JRVFWdVgvRDZGc0RGak5sdlNLWng2SmNVMUhmb0txbktjeWdPbkt5WHVQNENkdGgyY2FJNUdNNQpQRGc0N2dXcVE3cFBnN25HSVlLVnF1cHZyejRrN3B0S0xUZ2pRK0xaSTFJdzY2Q1BxajBDZ0RmTWpSdVF1MDB1CmVUK3hNNDhxZkUvc0Q4Z2RrWlVFdGF1cWduQUJtcnJhZ0xtenlJK3N0QVdWU2NyUWRSZTkvM1RYTzlBS1I0TDYKOExIb3A1WVpmKzBaZnVrTU9abnVQS1RiaFpHZnlkNmhxa2h1VGdDRlVxR3FCdEhyWWcvK0QyOFp4eDFtbXhXKworbWd3ZUJVblJzY2l5d0tDQVFFQTJzODhNV3BtbjhzLyt3bVp3WWo5OWVyRExrS0tybjFPWW4rSnFUU1E3RHhJCnRMRDlVYmJkMXA3cm1lZE9aRWhEQy9OdnYyc1BGeUZlcDVwc3FxczNmT3M2Y3BwRzc4WjgrK1p0OHNnREFiaFQKZDRHblVaazIwckJIMlVGQ0h6UWI2cS9YSmRWa2JFL0VueUxlRHR1aWxoZ0c2dWxtYm5CeG5Nc01HVzRoak5leQovWlYwWWRQZE91OWVUaC92NVpEVm9KbUZvWVFZblQ5cEEzQmRqYWR6dXdnN3NET05XV25ld2JBcytERkFxQVVmCkNMQW5Ed3VqbEFZSThDamFpZGRaVG5Rbm0ySldyTnZKdmJVamNQU1U5S1dabnF4MVdCNzJYTlMyN2h6cTNCQlMKYlc0NDFFcVI1ME1WbFd1VGt5dlMzQ0tCM2R1Z2QrTUY0WmVTMVZVOU1RS0NBUUVBZ3hhNVlQUjlzOE5TWmpQQwpHMDFKQjNxemxhVkZKYlpxL2lLd0l5SnQ2KzM1VWNtNXhhL1NUVHk2UnAweW9CclNuc0Y0TkxJZ0RuL1kwVEN6CkFYelh0dWtyeXJySFBMSkdOd0tmbm0zMitrWVNhWlNTQ29tMm1oZTJTeisvN0lrNVJFMUtNS3ZBZHNiQXQ2KzIKNldZNmgzWi9NYzdpNTNkanZYaVdRRHZEUHpIbWx6Y1NMYTJtTXNIOTV4aW1jdi91NmptMXA4TjljcW13RnczeQpUUlZCY1hGdHlhRis0Z3VhcGhWK3NWcDc3M3FqdU56NTVmb0lZV0hFNWtucEh0NW5KVjlYS3plY1AvNjRzZFh3CmwrNFRLaHJ6eHNOZmYySjQrcFJrQS93V2kzSERHVWUzTytNdmVKUFpsdWkrbGlIYVFWa1BpT2haa00xZFlwa1IKNGpaZHd3S0NBUUJzQVJEb0gyb0toQXZQd1J4cEFGTEMrUjlnalMzaEZTOEV4WWxRd1FhcjVOSEtodlp6U0QxVgorOW0xZlF3ZnlkOTJYYklTSFNrMHRKOEJRZU5UbHZIcnNqeUdad3FPdmozaEpRdXVZL1cvK3BrUWl5bm95Q1RjCmVIRHVseHlwUkZKblZHWnhZVlNSZGdwS3RxNC9UVUNDcjlkeVNzVHB6SXozNU8zUys1Nko0OHFSQ3gySVVFaUsKRjY5SUJ0R21VZ2h3bm5ic2s4U0drYzhuQ0diVlRndDlEWUpRNWhGbVNqRFBFRVFTT2xWODJoSkllcEs5QlhTMwowd2JFYkpYNnBoYUorQ0c0dkNDbWNGS3pWbDdwR1lFUkJWQy9sc2JST1c5SHdTT09neTJXZEdRTGFmV1pMRG02Cm1rMWtGTmFpTldaK2pIWG42Y25hZzIvYXU3T1pvOXB4QW9JQkFDNFZJbUZPL0dJQStJbmVHTjRacXlNMlE3cjEKYmRCeFlZTWNPOG5RV1FSUXBuWFJSdzlLQ3gvU2xNNWNXTGoxV3FoTnZtQ0V4Sjh1WTRzRmg4MnNCaUpodXRGeAo3ZTNsZ0ZDRmVNTGRleUVHa3lTNjlnakNrRkZVNEhCUWtIVXQyMVY0Y0hlbEN5YlJLa2NVTDh6UDFsNEZ2bDJBCnNkcFVtenNNZlByRTJhK0RWZGxTK0dxTENvMFpsTzE0dHNwMk1UQWU3RUMrWndaVElDcHZGcnBpam81WUNma04KQ2wwZ3pxaUZsVWxSc0xPa0RJaWtUT2VCU2o1ditieWsreCt0S3NKSSt4TkIvREJBQTlIWjlSWE9XQzkzcFhUQwo1cXlpM09uV2x5bCt0VTBSVVhzREFSakswWkZHZW1JY0pxRUVmZU5MUzN5ZGZ0NmMrQkwvMHpwR0NtWT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: nifi-mtls-ca-secret-v2
  namespace: nifi
  labels:
    controller.cert-manager.io/fao: "true"
type: kubernetes.io/tls
---
---
# Self-signed issuer для создания внутреннего CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nifi-internal-selfsigned
  namespace: nifi
spec:
  selfSigned: {}
---
# Issuer использующий внутренний CA
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nifi-internal-ca-issuer
  namespace: nifi
spec:
  ca:
    # ИСПРАВЛЕНИЕ: Issuer тоже должен читать из правильного секрета
    secretName: nifi-mtls-ca-secret-v2
---
---
# Внутренний сертификат NiFi для internal Service DNS
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-internal-tls
  namespace: nifi
spec:
  secretName: nifi-internal-tls-secret
  duration: 8760h # 1 год
  renewBefore: 720h # 30 дней до истечения
  subject:
    organizations:
      - NiFi Internal
  commonName: nificl.nifi.svc.cluster.local
  dnsNames:
    # Внешний домен для корректной работы SNI в NiFi 2.0+ (Jetty 12)
    - nifi.kube5s.ru
    # Внутренние Kubernetes DNS имена
    - nificl.nifi.svc.cluster.local
    - nificl.nifi.svc
    - "*.nifi.svc.cluster.local"
    - "*.nifi.svc"
    # Headless service для каждой ноды
    - nificl-0.nificl.nifi.svc.cluster.local
    - nificl-0.nificl.nifi.svc
    # Если добавятся еще ноды:
    # - nificl-1.nificl.nifi.svc.cluster.local
    # - nificl-2.nificl.nifi.svc.cluster.local
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  issuerRef:
    name: nifi-internal-ca-issuer
    kind: Issuer
---
---
# Клиентский сертификат для аутентификации NiFi в Registry
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nificl-sa-cert
  namespace: nifi
spec:
  secretName: nificl-sa-cert
  duration: 8760h  # 1 год
  renewBefore: 720h  # Обновлять за 30 дней до истечения
  
  # Organization removed to match strict DN in users.xml
  # subject:
  #   organizations:
  #     - "NiFi"
  
  commonName: "nifi-operator-client"
  
  # Клиентская аутентификация
  usages:
    - client auth
    - digital signature
    - key encipherment
  
  privateKey:
    algorithm: RSA
    size: 4096
  
  # Использовать CA Issuer
  issuerRef:
    name: nifi-internal-ca-issuer
    kind: Issuer
    group: cert-manager.io
